project_id = "ftejarickpnxucpungck"

[functions.delete-user-account]
verify_jwt = true

[functions.autopay-webhook]
verify_jwt = false

[functions.autopay-initiate-payment]
verify_jwt = false

[functions.autopay-verify-return]
verify_jwt = false

[functions.med24-create-visit]
verify_jwt = false

[functions.med24-get-visit]
verify_jwt = false

[functions.med24-upload-files]
verify_jwt = false

[functions.generate-case-pdf]
verify_jwt = false

[functions.create-case-for-payment]
verify_jwt = false
